; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = nanoatmega328new
framework = arduino

[env:testing_servo]
build_src_filter = 
    -<*>
    ; +<servo_stuff.cpp>
    ; +<servo_stuff.c>
lib_deps = https://github.com/arduino-libraries/Servo.git

[env:nano_testing]
build_src_filter = 
    -<*>
    ; +<blinkLED_reg.c>
    +<uart-button.c>
